/**
 * Apply supabase/schema.sql via Supabase Management API, then seed admin.
 *
 * Requires:
 *   SUPABASE_ACCESS_TOKEN  (https://supabase.com/dashboard/account/tokens)
 *   Optional: SUPABASE_ORG_ID, SUPABASE_DB_PASSWORD, ADMIN_*
 *
 * Usage: node --env-file=.env scripts/provision_supabase.js
 */
import { createClient } from '@supabase/supabase-js';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { randomBytes } from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const token = process.env.SUPABASE_ACCESS_TOKEN;
const orgId = process.env.SUPABASE_ORG_ID;
const projectName = process.env.SUPABASE_PROJECT_NAME || 'chesslogs';
const region = process.env.SUPABASE_REGION || 'us-east-1';
const dbPassword = process.env.SUPABASE_DB_PASSWORD || `Cl${randomBytes(12).toString('base64url')}!a1`;

if (!token) {
  console.error('Set SUPABASE_ACCESS_TOKEN (create at https://supabase.com/dashboard/account/tokens)');
  process.exit(1);
}

const api = 'https://api.supabase.com/v1';

async function apiFetch(path, options = {}) {
  const res = await fetch(`${api}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      ...(options.headers || {}),
    },
  });
  const text = await res.text();
  let body;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    body = text;
  }
  if (!res.ok) {
    throw new Error(`${options.method || 'GET'} ${path} → ${res.status}: ${typeof body === 'string' ? body : JSON.stringify(body)}`);
  }
  return body;
}

async function resolveOrgId() {
  if (orgId) return orgId;
  const orgs = await apiFetch('/organizations');
  if (!Array.isArray(orgs) || orgs.length === 0) {
    throw new Error('No Supabase organizations found for this token');
  }
  console.log('Using org:', orgs[0].id, orgs[0].name);
  return orgs[0].id;
}

async function findOrCreateProject(organizationId) {
  const projects = await apiFetch('/projects');
  const existing = (projects || []).find((p) => p.name === projectName);
  if (existing) {
    console.log('Reusing existing project:', existing.id, existing.name);
    return existing;
  }

  console.log(`Creating project "${projectName}" in ${region}...`);
  const created = await apiFetch('/projects', {
    method: 'POST',
    body: JSON.stringify({
      name: projectName,
      organization_id: organizationId,
      region,
      db_pass: dbPassword,
    }),
  });
  return created;
}

async function waitHealthy(ref) {
  for (let i = 0; i < 60; i++) {
    const p = await apiFetch(`/projects/${ref}`);
    const status = p.status || p.health || p.state;
    console.log(`Project status: ${status || JSON.stringify(p).slice(0, 120)}`);
    if (String(status).toLowerCase() === 'active_healthy' || String(status).toLowerCase() === 'active') {
      return p;
    }
    await new Promise((r) => setTimeout(r, 5000));
  }
  throw new Error('Timed out waiting for project to become healthy');
}

async function getApiKeys(ref) {
  const keys = await apiFetch(`/projects/${ref}/api-keys`);
  const anon = keys.find((k) => k.name === 'anon' || k.tags?.includes('anon'));
  const service = keys.find((k) => k.name === 'service_role' || k.tags?.includes('service_role'));
  if (!anon?.api_key || !service?.api_key) {
    throw new Error('Could not resolve anon/service_role keys: ' + JSON.stringify(keys));
  }
  return { anon: anon.api_key, service: service.api_key };
}

async function runSql(ref, query) {
  return apiFetch(`/projects/${ref}/database/query`, {
    method: 'POST',
    body: JSON.stringify({ query }),
  });
}

function writeEnv({ url, anon, service }) {
  const envPath = resolve(root, '.env');
  const existing = existsSync(envPath) ? readFileSync(envPath, 'utf8') : '';
  const adminEmail = process.env.ADMIN_EMAIL || 'coach@chesslogs.com';
  const adminPassword = process.env.ADMIN_PASSWORD || 'ChessLogsAdmin2026!';
  const adminName = process.env.ADMIN_NAME || 'Head Coach';

  const next = `# Generated by scripts/provision_supabase.js — DO NOT COMMIT
VITE_SUPABASE_URL=${url}
VITE_SUPABASE_ANON_KEY=${anon}
VITE_CHESSCOM_OAUTH_ENABLED=false
SUPABASE_SERVICE_ROLE_KEY=${service}
ADMIN_EMAIL=${adminEmail}
ADMIN_PASSWORD=${adminPassword}
ADMIN_NAME="${adminName}"
SUPABASE_DB_PASSWORD=${dbPassword}
SUPABASE_ACCESS_TOKEN=${token}
`;

  // Prefer rewrite generated file; keep any unrelated keys only if file empty of VITE_
  writeFileSync(envPath, existing.includes('VITE_SUPABASE_URL=') ? next : `${existing}\n${next}`.trim() + '\n');
  console.log('Wrote', envPath);
  return { adminEmail, adminPassword, adminName };
}

async function seedAdmin({ url, service, adminEmail, adminPassword, adminName }) {
  const supabase = createClient(url, service, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const { data: usersData, error: listError } = await supabase.auth.admin.listUsers();
  if (listError) throw listError;

  let user = usersData.users.find((u) => u.email?.toLowerCase() === adminEmail.toLowerCase());
  if (!user) {
    const { data, error } = await supabase.auth.admin.createUser({
      email: adminEmail,
      password: adminPassword,
      email_confirm: true,
      user_metadata: { role: 'admin', display_name: adminName },
    });
    if (error) throw error;
    user = data.user;
  }

  const { data: profile, error: profileError } = await supabase
    .from('profiles')
    .upsert({ id: user.id, role: 'admin', display_name: adminName }, { onConflict: 'id' })
    .select()
    .single();
  if (profileError) throw profileError;

  console.log('Seeded admin:', { email: adminEmail, id: profile.id, role: profile.role });
}

async function main() {
  const organizationId = await resolveOrgId();
  const project = await findOrCreateProject(organizationId);
  const ref = project.id || project.ref;
  await waitHealthy(ref);

  const url = `https://${ref}.supabase.co`;
  const { anon, service } = await getApiKeys(ref);

  const schema = readFileSync(resolve(root, 'supabase/schema.sql'), 'utf8');
  console.log('Applying schema.sql...');
  // Management API may reject multi-statement bundles; split on semicolons carefully enough for our file
  const statements = schema
    .split(/;\s*\n/)
    .map((s) => s.trim())
    .filter((s) => s && !s.startsWith('--'));

  for (const statement of statements) {
    const sql = statement.endsWith(';') ? statement : `${statement};`;
    try {
      await runSql(ref, sql);
    } catch (err) {
      // Idempotent re-runs: ignore already-exists style noise when possible
      const msg = String(err.message || err);
      if (/already exists/i.test(msg)) {
        console.warn('skip (exists):', sql.slice(0, 60).replace(/\s+/g, ' '), '...');
        continue;
      }
      throw err;
    }
  }

  const adminCreds = writeEnv({ url, anon, service });
  await seedAdmin({ url, service, ...adminCreds });
  console.log('✅ Supabase provisioned. Project URL:', url);
}

main().catch((err) => {
  console.error('FAIL', err.message || err);
  process.exit(1);
});
